//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.WebApi.FinancialService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceStructureDTO", Namespace="http://schemas.datacontract.org/2004/07/CdT.eConnect.DTOs")]
    [System.SerializableAttribute()]
    public partial class PriceStructureDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BasePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SurchargeComplexityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SurchargeConfidentialityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SurchargeNonEuLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SurchargeWebUploadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TarifIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BasePrice {
            get {
                return this.BasePriceField;
            }
            set {
                if ((this.BasePriceField.Equals(value) != true)) {
                    this.BasePriceField = value;
                    this.RaisePropertyChanged("BasePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SurchargeComplexity {
            get {
                return this.SurchargeComplexityField;
            }
            set {
                if ((this.SurchargeComplexityField.Equals(value) != true)) {
                    this.SurchargeComplexityField = value;
                    this.RaisePropertyChanged("SurchargeComplexity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SurchargeConfidentiality {
            get {
                return this.SurchargeConfidentialityField;
            }
            set {
                if ((this.SurchargeConfidentialityField.Equals(value) != true)) {
                    this.SurchargeConfidentialityField = value;
                    this.RaisePropertyChanged("SurchargeConfidentiality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SurchargeNonEuLanguage {
            get {
                return this.SurchargeNonEuLanguageField;
            }
            set {
                if ((this.SurchargeNonEuLanguageField.Equals(value) != true)) {
                    this.SurchargeNonEuLanguageField = value;
                    this.RaisePropertyChanged("SurchargeNonEuLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SurchargeWebUpload {
            get {
                return this.SurchargeWebUploadField;
            }
            set {
                if ((this.SurchargeWebUploadField.Equals(value) != true)) {
                    this.SurchargeWebUploadField = value;
                    this.RaisePropertyChanged("SurchargeWebUpload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TarifId {
            get {
                return this.TarifIdField;
            }
            set {
                if ((this.TarifIdField.Equals(value) != true)) {
                    this.TarifIdField = value;
                    this.RaisePropertyChanged("TarifId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinancialService.IFinancialService")]
    public interface IFinancialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialService/GetPrice", ReplyAction="http://tempuri.org/IFinancialService/GetPriceResponse")]
        ClientPortal.WebApi.FinancialService.PriceStructureDTO GetPrice(string serviceType, string priority, System.DateTime referenceDate, string sourceLanguage, string targetLanguage, string sourceFormat, bool isConfidential, decimal quantity, int organizationId, bool hasReduction, string deliveryMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialService/GetPrice", ReplyAction="http://tempuri.org/IFinancialService/GetPriceResponse")]
        System.Threading.Tasks.Task<ClientPortal.WebApi.FinancialService.PriceStructureDTO> GetPriceAsync(string serviceType, string priority, System.DateTime referenceDate, string sourceLanguage, string targetLanguage, string sourceFormat, bool isConfidential, decimal quantity, int organizationId, bool hasReduction, string deliveryMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialService/GetPriceRecalculated", ReplyAction="http://tempuri.org/IFinancialService/GetPriceRecalculatedResponse")]
        ClientPortal.WebApi.FinancialService.PriceStructureDTO GetPriceRecalculated(string serviceType, string priority, System.DateTime referenceDate, string sourceLanguage, string targetLanguage, string sourceFormat, bool isConfidential, decimal originalQuantity, decimal builtQuantity, int organizationId, bool hasReduction, string deliveryMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialService/GetPriceRecalculated", ReplyAction="http://tempuri.org/IFinancialService/GetPriceRecalculatedResponse")]
        System.Threading.Tasks.Task<ClientPortal.WebApi.FinancialService.PriceStructureDTO> GetPriceRecalculatedAsync(string serviceType, string priority, System.DateTime referenceDate, string sourceLanguage, string targetLanguage, string sourceFormat, bool isConfidential, decimal originalQuantity, decimal builtQuantity, int organizationId, bool hasReduction, string deliveryMode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinancialServiceChannel : ClientPortal.WebApi.FinancialService.IFinancialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialServiceClient : System.ServiceModel.ClientBase<ClientPortal.WebApi.FinancialService.IFinancialService>, ClientPortal.WebApi.FinancialService.IFinancialService {
        
        public FinancialServiceClient() {
        }
        
        public FinancialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientPortal.WebApi.FinancialService.PriceStructureDTO GetPrice(string serviceType, string priority, System.DateTime referenceDate, string sourceLanguage, string targetLanguage, string sourceFormat, bool isConfidential, decimal quantity, int organizationId, bool hasReduction, string deliveryMode) {
            return base.Channel.GetPrice(serviceType, priority, referenceDate, sourceLanguage, targetLanguage, sourceFormat, isConfidential, quantity, organizationId, hasReduction, deliveryMode);
        }
        
        public System.Threading.Tasks.Task<ClientPortal.WebApi.FinancialService.PriceStructureDTO> GetPriceAsync(string serviceType, string priority, System.DateTime referenceDate, string sourceLanguage, string targetLanguage, string sourceFormat, bool isConfidential, decimal quantity, int organizationId, bool hasReduction, string deliveryMode) {
            return base.Channel.GetPriceAsync(serviceType, priority, referenceDate, sourceLanguage, targetLanguage, sourceFormat, isConfidential, quantity, organizationId, hasReduction, deliveryMode);
        }
        
        public ClientPortal.WebApi.FinancialService.PriceStructureDTO GetPriceRecalculated(string serviceType, string priority, System.DateTime referenceDate, string sourceLanguage, string targetLanguage, string sourceFormat, bool isConfidential, decimal originalQuantity, decimal builtQuantity, int organizationId, bool hasReduction, string deliveryMode) {
            return base.Channel.GetPriceRecalculated(serviceType, priority, referenceDate, sourceLanguage, targetLanguage, sourceFormat, isConfidential, originalQuantity, builtQuantity, organizationId, hasReduction, deliveryMode);
        }
        
        public System.Threading.Tasks.Task<ClientPortal.WebApi.FinancialService.PriceStructureDTO> GetPriceRecalculatedAsync(string serviceType, string priority, System.DateTime referenceDate, string sourceLanguage, string targetLanguage, string sourceFormat, bool isConfidential, decimal originalQuantity, decimal builtQuantity, int organizationId, bool hasReduction, string deliveryMode) {
            return base.Channel.GetPriceRecalculatedAsync(serviceType, priority, referenceDate, sourceLanguage, targetLanguage, sourceFormat, isConfidential, originalQuantity, builtQuantity, organizationId, hasReduction, deliveryMode);
        }
    }
}
