export enum LookupNames {
    // RequestTypes = 'requestTypes',
    // Statuses = 'status',
    // Clients = 'Clients',
    // Purposes = 'Purposes',
    // DeliveryModes = 'DeliveryModes',
    // RequestTemplate = 'RequestTemplates',
    // Departments = 'Departments',
    // Document = 'SourceMaterialDocumentFormatExtensionss'
    clients = 'clients',
    departments = 'departments',
    contacts = 'contacts',
    countries = 'countries',
    currencies = 'currencies',
    purposes = 'purposes',
    languages = 'languages',
    domains = 'domains',
    services = 'services',
    priorities = 'priorities',
    statuses = 'statuses',
    asaStatuses = 'asaStatuses',
    requestSubStatuses = 'requestSubStatuses',
    documentFormatTargets = 'documentFormatTargets',
    documentFormats = 'documentFormats',
    documentFormatExtensions = 'documentFormatExtensions',
    sourceMaterialDocumentFormatExtensionsWS = 'sourceMaterialDocumentFormatExtensionsWS',
    sourceMaterialDocumentFormatExtensions = 'sourceMaterialDocumentFormatExtensions',
    sourceMaterialDocumentFormats = 'sourceMaterialDocumentFormats',
    materialClassifications = 'materialClassifications',
    unitConversions = 'unitConversions',
    unitTypes = 'unitTypes',
    units = 'units',
    deliveryModes = 'deliveryModes',
    turnaroundTimes = 'turnaroundTimes',
    holidays = 'holidays',
    jobStatuses = 'jobStatuses',
    taskDefinitions = 'taskDefinitions',
    globalParameters = 'globalParameters',
    requestTypes = 'requestTypes',
    confidentialities = 'confidentialities'
}


