using Breeze.ContextProvider;
using System;
using System.Collections.Generic;
using System.Dynamic;

namespace ClientPortal.Helpers
{
    public static class Breeze
    {
        /// <summary>
        /// Add an entity to the SaveMap
        /// </summary>
        /// <param name="saveMap">The saveMap where to add the entity</param>
        /// <param name="entityToAdd">The entity to add to the SaveMap</param>
        /// <param name="context">The breeze context to use</param>
        public static void AddCustomEntity(this Dictionary<Type, List<EntityInfo>> saveMap, object entityToAdd, ContextProvider context, EntityState entityState = EntityState.Modified, bool forceUpdate = true)
        {
            Type typeOfEntityToAdd = entityToAdd.GetType();
            _addCustomentity(saveMap, entityToAdd, typeOfEntityToAdd, context, entityState, forceUpdate);
        }

        /// <summary>
        /// Add an entity to the SaveMap
        /// </summary>
        /// <param name="saveMap">The saveMap where to add the entity</param>
        /// <param name="entityToAdd">The entity to add to the SaveMap</param>
        /// <param name="context">The breeze context to use</param>
        /// <typeparam name="T">Entity type</typeparam>
        public static void AddCustomEntity<T>(this Dictionary<Type, List<EntityInfo>> saveMap, object entityToAdd, ContextProvider context, EntityState entityState = EntityState.Modified, bool forceUpdate = true)
        {
            Type typeOfEntityToAdd = typeof(T);
            _addCustomentity(saveMap, entityToAdd, typeOfEntityToAdd, context, entityState, forceUpdate);
        }

        #region help/auxiliary methods

        private static void _addCustomentity(Dictionary<Type, List<EntityInfo>> saveMap, object entityToAdd, Type typeOfEntityToAdd, ContextProvider context, EntityState entityState = EntityState.Modified, bool forceUpdate = true)
        {
            List<EntityInfo> entityInfoList = new List<EntityInfo>();

            // check if the type exists in the savemap, if not create it
            if (!saveMap.ContainsKey(typeOfEntityToAdd))
            {
                saveMap.Add(typeOfEntityToAdd, entityInfoList);
            }
            else
            {
                saveMap.TryGetValue(typeOfEntityToAdd, out entityInfoList);
            }

            EntityInfo entity = context.CreateEntityInfo(entityToAdd, entityState);
            entity.ForceUpdate = forceUpdate;
            entity.OriginalValuesMap = new Dictionary<string, object>();
            entity.UnmappedValuesMap = new Dictionary<string, object>();

            if (entity.AutoGeneratedKey == null)
            {
                dynamic autoGeneratedKey = new ExpandoObject();
                autoGeneratedKey.propertyName = "Id";
                autoGeneratedKey.autoGeneratedKeyType = AutoGeneratedKeyType.KeyGenerator.ToString();
                entity.AutoGeneratedKey = new AutoGeneratedKey(entityToAdd, autoGeneratedKey);
            }

            entityInfoList.Add(entity);
        }

        #endregion
    }
}